name: Limpeza Workspace

on:
  workflow_call:
    inputs:
      diretorio:
        required: true
        type: string
        description: "Diretório a ser limpo"
    secrets:
      MS_TEAMS_WEBHOOK_URI:
        required: true

jobs:
  limpeza_workspace:
    runs-on: [self-hosted]

    steps:
    - name: Limpeza Workspace
      id: limpeza_workspace
      run: |
        echo "Iniciando limpeza do workspace"
        echo "Diretório a ser limpo: ${{ inputs.diretorio }}"
        
        # Aguardar um pouco para garantir que os processos do workflow anterior tenham sido encerrados
        Start-Sleep -Seconds 30
        
        $diretorio = "${{ inputs.diretorio }}"
        
        # Verificar se o diretório existe
        if (-not (Test-Path $diretorio)) {
            Write-Host "O diretório do workspace não existe: $diretorio"
            exit 0
        }

        # Navegar para o diretório do workspace
        Set-Location -Path $diretorio
        Write-Host "Diretório atual: $(Get-Location)"

        # Limpar apenas os arquivos do projeto atual usando git, se .git existir
        if (Test-Path .git) {
            Write-Host "Executando limpeza git"
            git reset --hard
            git clean -fdx
        } else {
            Write-Host "Diretório .git não encontrado. Pulando comandos git."
        }
        
        # Limpar o diretório
        try {
            Write-Host "Removendo o conteúdo do diretório: $diretorio"
            Remove-Item -Path "$diretorio\*" -Recurse -Force -ErrorAction Stop
            Write-Host "Conteúdo do diretório removido com sucesso"
        }
        catch {
            Write-Host "Erro ao remover o conteúdo do diretório: $_"
            exit 1
        }

        # Verificar se o diretório está vazio
        $conteudoRestante = Get-ChildItem -Path $diretorio -Force
        if ($conteudoRestante) {
            Write-Host "Aviso: Alguns itens não puderam ser removidos:"
            $conteudoRestante | ForEach-Object { Write-Host $_.FullName }
        } else {
            Write-Host "O diretório está completamente vazio"
        }
      shell: pwsh
