name: Limpeza Workspace

on:
  workflow_call:
    inputs:
      diretorio:
        required: true
        type: string
        description: "Diretório a ser limpo"
    secrets:
      MS_TEAMS_WEBHOOK_URI:
        required: true

jobs:
  limpeza_workspace:
    runs-on: [self-hosted]

    steps:
    - name: Limpeza Workspace
      id: limpeza_workspace
      run: |
        echo "Iniciando limpeza do workspace"
        echo "Diretório a ser limpo: ${{ inputs.diretorio }}"
        
        $diretorio = "${{ inputs.diretorio }}"
        
        # Verificar se o diretório existe
        if (-not (Test-Path $diretorio)) {
            Write-Host "O diretório do workspace não existe: $diretorio"
            exit 0
        }

        # Navegar para o diretório do workspace
        Set-Location -Path $diretorio
        Write-Host "Diretório atual: $(Get-Location)"

        # Configurar o diretório como seguro (similar ao que o checkout faz)
        git config --global --add safe.directory $diretorio

        # Obter a URL do repositório remoto
        $remoteUrl = git config --local --get remote.origin.url
        Write-Host "URL do repositório remoto: $remoteUrl"

        # Limpar o repositório
        Write-Host "Limpando o repositório"
        git clean -ffdx
        if ($LASTEXITCODE -ne 0) {
            Write-Host "Erro ao executar git clean"
            exit 1
        }
        
        git reset --hard HEAD
        if ($LASTEXITCODE -ne 0) {
            Write-Host "Erro ao executar git reset"
            exit 1
        }
        
        # Desabilitar coleta de lixo automática
        git config --local gc.auto 0

        Write-Host "Limpeza do workspace concluída"
      shell: pwsh
